name: build-docker-image

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the image'
        required: true
        default: 'latest'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v4'
        with:
          repository: nvcnvn/F5-TTS
      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set image tag (lowercase repository)
        id: prep
        run: |
          REPO_LC=$(echo "${REPO}" | tr '[:upper:]' '[:lower:]')
          echo "TAG=ghcr.io/${REPO_LC}:${TAG}-cpu" >> $GITHUB_ENV
        env:
          REPO: ${{ github.repository }}
          TAG: ${{ github.event.inputs.tag_name }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.TAG }}
